- nodeset:
    name: ara-infra-fedora-29
    nodes:
      - name: ara.recordsansible.org
        label: fedora-29

- job:
    name: ara-infra-website
    parent: base
    nodeset: ara-infra-fedora-29
    pre-run: tests/website-pre.yaml
    run: playbooks/website.yaml
    post-run: tests/website-post.yaml
    success-url: logs/build/

- job:
    name: ara-infra-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors recordsansible/ara-infra to ansible-community/ara-infra
    allowed-projects: recordsansible/ara-infra
    vars:
      git_mirror_repository: ansible-community/ara-infra
    secrets:
      - name: git_mirror_credentials
        secret: ara_git_mirror_credentials
        pass-to-parent: true

- project:
    check:
      jobs:
        - ara-infra-website
    gate:
      jobs:
        - ara-infra-website
    post:
      jobs:
        - ara-infra-upload-git-mirror
