# https://gohugo.io/getting-started/configuration/

languageCode = "en-us"
title = "ARA Records Ansible | ara.recordsansible.org"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 10
pluralizeListTitles = false
enableRobotsTXT = true
enableGitInfo = true
relativeURLs = true

[params]
  categoriesByCount      = true
  cssFiles               = ["default"]
  description            = "ARA Records Ansible and makes it easier to understand and troubleshoot."
  dynamicTitles          = false
  enableCDN              = false
  faviconVersion         = ""
  hideEmptyStats         = false
  highlightjsLang        = ["bash", "python", "yaml"]
  highlightjsTheme       = "github"
  highlightjs            = true
  imageStretch           = ""
  jsFiles                = ["default"]
  loadFavicon            = true
  navbarTitle            = "ARA Records Ansible"
  readingTime            = true
  removeBlur             = false
  rssAppearAtBottom      = true
  rssAppearAtTop         = true
  showSidebarCategories  = true
  socialShare            = []
  viewMorePostsLink      = "/blog/"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[params.intro]
  paragraph = "Records Ansible and makes it easier to understand and troubleshoot."
  [params.intro.pic]
    src       = "static/logo.png"
    circle    = false
    imperfect = false
    width     = ""
    alt       = "ara.recordsansible.org"

# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
[markup.goldmark.renderer]
unsafe = true

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 8

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "About"
  url = "/"
  identifier = "fa fa-question-circle"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  identifier = "fa fa-newspaper-o"
  weight = 2

[[menu.main]]
  name = "Code"
  url = "https://github.com/ansible-community/ara"
  identifier = "fa fa-github"
  weight = 3

[[menu.main]]
  name = "Documentation"
  url = "https://ara.readthedocs.io"
  identifier = "fa fa-book"
  weight = 4

[[menu.main]]
  name = "Demo"
  url = "https://demo.recordsansible.org"
  identifier = "fa fa-external-link"
  weight = 5

[[menu.main]]
  name = "Community & Help"
  url = "/community"
  identifier = "fa fa-users"
  weight = 6

[social]
  github           = "ansible-community/?q=ara"
  twitter          = "RecordsAnsible"
