# Copyright (c) 2022 The ARA Records Ansible authors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

# See host_vars/infra.recordsansible.org.yaml for role variables
- name: Provision the live demo for demo.recordsansible.org
  hosts: infra.recordsansible.org
  gather_facts: yes
  tasks:
    - name: Install and configure MySQL (thanks geerlingguy!)
      include_role:
        name: geerlingguy.mysql
        # The role expects to run as root
        apply:
          become: true

    # This role elevates privileges by itself only when necessary
    - name: Deploy an ara API server with gunicorn and nginx in front
      include_role:
        name: recordsansible.ara.ara_api
