- name: Provision demo.recordsansible.org
  hosts: demo.recordsansible.org
  gather_facts: yes
  vars:
    # ara_api
    ara_api_fqdn: api.demo.recordsansible.org
    ara_api_frontend_server: nginx
    ara_api_frontend_vhost: api.demo.recordsansible.org.conf.j2
    ara_api_wsgi_server: gunicorn
    ara_api_allowed_hosts:
      - api.demo.recordsansible.org
    ara_api_cors_origin_whitelist:
      - web.demo.recordsansible.org
      - logs.openstack.org
    # ara_web
    ara_web_fqdn: web.demo.recordsansible.org
    ara_web_api_endpoint: "https://api.demo.recordsansible.org"
    ara_web_frontend_server: nginx
    ara_web_frontend_vhost: web.demo.recordsansible.org.conf.j2
  roles:
    - ara_api
    - ara_web
