- name: Provision demo.recordsansible.org
  hosts: demo.recordsansible.org
  gather_facts: yes
  vars:
    # ara_api
    ara_api_write_login_required: true
    ara_api_fqdn: api.demo.recordsansible.org
    ara_api_frontend_server: nginx
    ara_api_frontend_vhost: api.demo.recordsansible.org.conf.j2
    ara_api_wsgi_server: gunicorn
    ara_api_allowed_hosts:
      - api.demo.recordsansible.org
    # TODO: Figure out if it's possible to set ara-web to use demo from localhost:3000
    ara_api_cors_origin_allow_all: true
    ara_api_cors_origin_whitelist:
      - https://web.demo.recordsansible.org
      - http://logs.openstack.org
      - http://localhost:3000
    # ara_web
    ara_web_fqdn: web.demo.recordsansible.org
    ara_web_api_endpoint: "https://api.demo.recordsansible.org"
    ara_web_frontend_server: nginx
    ara_web_frontend_vhost: web.demo.recordsansible.org.conf.j2
  roles:
    - ara_api
    - ara_web
